-- NEXUS PROTOCOL DISCUSS SCHEMA V2
-- Run this in your Supabase SQL Editor

-- 1. Profiles Table (Enhanced)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    display_name TEXT,
    avatar_url TEXT,
    status TEXT DEFAULT 'online',
    pronouns TEXT,
    bio TEXT,
    banner_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Messages Table (Supports DMs, Groups, Global, & Media)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender UUID REFERENCES public.profiles(id) NOT NULL,
    sender_name TEXT NOT NULL,
    receiver TEXT NOT NULL, -- User UUID, Group ID, or 'global_chat'
    content TEXT,
    image_url TEXT, -- NEW: For image uploads
    channel_type TEXT NOT NULL, -- 'direct', 'group', 'global'
    is_media BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Groups Table
CREATE TABLE IF NOT EXISTS public.groups (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id UUID REFERENCES public.profiles(id),
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Group Members
CREATE TABLE IF NOT EXISTS public.group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id UUID REFERENCES public.groups(id),
    user_id UUID REFERENCES public.profiles(id),
    user_name TEXT,
    role TEXT DEFAULT 'member'
);

-- 5. Friend Requests
CREATE TABLE IF NOT EXISTS public.friend_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user UUID REFERENCES public.profiles(id),
    to_user UUID REFERENCES public.profiles(id),
    from_username TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'accepted', 'blocked'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS POLICIES (Privacy Hardening)
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see messages they sent or received" ON public.messages
    FOR SELECT USING (
        auth.uid() = sender OR 
        receiver = auth.uid()::text OR 
        receiver = 'global_chat' OR
        EXISTS (SELECT 1 FROM group_members WHERE group_id::text = receiver AND user_id = auth.uid())
    );

-- Enable Real-time (Replica)
ALTER PUBLICATION supabase_realtime ADD TABLE messages, profiles, friend_requests;
